# Form implementation generated from reading ui file 'e:\my\python_study\py\ModLibrary\uic_ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(480, 348)
        self.verticalLayout = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopBar = QtWidgets.QHBoxLayout()
        self.TopBar.setObjectName("TopBar")
        self.SearchBox = SearchLineEdit(parent=Main)
        self.SearchBox.setObjectName("SearchBox")
        self.TopBar.addWidget(self.SearchBox)
        self.RefreshButton = ToolButton(parent=Main)
        self.RefreshButton.setObjectName("RefreshButton")
        self.TopBar.addWidget(self.RefreshButton)
        self.AddModButton = ToolButton(parent=Main)
        self.AddModButton.setAutoRaise(False)
        self.AddModButton.setObjectName("AddModButton")
        self.TopBar.addWidget(self.AddModButton)
        self.verticalLayout.addLayout(self.TopBar)
        self.ModList = SingleDirectionScrollArea(parent=Main)
        self.ModList.setWidgetResizable(True)
        self.ModList.setObjectName("ModList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 460, 287))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ModList.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.ModList)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
from qfluentwidgets import SearchLineEdit, SingleDirectionScrollArea, ToolButton
