# Form implementation generated from reading ui file 'e:\my\python_study\py\ModLibrary\uic_ui\ModCard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModCard(object):
    def setupUi(self, ModCard):
        ModCard.setObjectName("ModCard")
        ModCard.resize(256, 80)
        ModCard.setMinimumSize(QtCore.QSize(0, 80))
        ModCard.setWindowTitle("ModCard")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ModCard)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ModIcon = IconWidget(parent=ModCard)
        self.ModIcon.setMinimumSize(QtCore.QSize(60, 60))
        self.ModIcon.setMaximumSize(QtCore.QSize(60, 60))
        self.ModIcon.setObjectName("ModIcon")
        self.horizontalLayout_2.addWidget(self.ModIcon)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ModName = StrongBodyLabel(parent=ModCard)
        self.ModName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ModName.setText("")
        self.ModName.setObjectName("ModName")
        self.horizontalLayout.addWidget(self.ModName)
        self.ModAuthors = CaptionLabel(parent=ModCard)
        self.ModAuthors.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ModAuthors.setText("")
        self.ModAuthors.setWordWrap(True)
        self.ModAuthors.setObjectName("ModAuthors")
        self.horizontalLayout.addWidget(self.ModAuthors)
        self.More = TransparentToolButton(parent=ModCard)
        self.More.setMinimumSize(QtCore.QSize(0, 20))
        self.More.setMaximumSize(QtCore.QSize(30, 30))
        self.More.setObjectName("More")
        self.horizontalLayout.addWidget(self.More)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ModDesc = BodyLabel(parent=ModCard)
        self.ModDesc.setText("")
        self.ModDesc.setWordWrap(True)
        self.ModDesc.setObjectName("ModDesc")
        self.verticalLayout.addWidget(self.ModDesc)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ModCard)
        QtCore.QMetaObject.connectSlotsByName(ModCard)

    def retranslateUi(self, ModCard):
        pass
from qfluentwidgets import BodyLabel, CaptionLabel, CardWidget, IconWidget, StrongBodyLabel, TransparentToolButton
